package clases;
// Generated 8 ene 2025, 19:08:51 by Hibernate Tools 5.6.15.Final

/**
 * LlevaId generated by hbm2java
 */
public class LlevaId implements java.io.Serializable {

	private int numetapa;
	private int codigocamiseta;

	public LlevaId() {
	}

	public LlevaId(int numetapa, int codigocamiseta) {
		this.numetapa = numetapa;
		this.codigocamiseta = codigocamiseta;
	}

	public int getNumetapa() {
		return this.numetapa;
	}

	public void setNumetapa(int numetapa) {
		this.numetapa = numetapa;
	}

	public int getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(int codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LlevaId))
			return false;
		LlevaId castOther = (LlevaId) other;

		return (this.getNumetapa() == castOther.getNumetapa())
				&& (this.getCodigocamiseta() == castOther.getCodigocamiseta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumetapa();
		result = 37 * result + this.getCodigocamiseta();
		return result;
	}

}
